# Generated by Django 4.1.3 on 2022-11-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstable',
            table='orders_table',
        ),
    ]
