# Generated by Django 4.1.3 on 2022-11-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsTable',
        ),
    ]
