# Generated by Django 4.1.3 on 2022-11-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_productstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
    ]
