# Generated by Django 4.1.3 on 2022-11-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productstable',
            table='products_table',
        ),
    ]
